name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Use 'zulu' to keep the distribution explicit and consistent
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package -B  # The '-B' option (Batch mode) makes Maven less verbose and more suitable for CI environments

      - name: Upload WAR file
        uses: actions/upload-artifact@v4
        with:
          name: verademo.war
          path: target/verademo.war
